TRUNCATE
    ediary.subject_to_class,
    ediary.teacher_to_class,
    ediary.teacher_to_subject,
    ediary.class_history,
    ediary.mark,
    ediary.task,
    ediary.lesson,
    ediary.teacher,
    ediary.student,
    ediary.class,
    ediary.subject;
